
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: add pnpm
        run: npm i pnpm -g

      - name: pnpm i
        run: pnpm i

      - name: test
        run: npx jest & pnpm run coverage
