
name: TEST
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
     runs-on: ubuntu-latest
     steps:
      - name: jest test
      - uses: actions/setup-node@v1
        with:
            node-version: '14.x'
      - run: pnpm i
      - run: pnpm run test
