name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
      - name: jest test
        with:
            node-version: '14.x'

      - name: Run pnpm i
        run: pnpm i

      - name: Run pnpm run test
        run: pnpm run test
