
name: TEST
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
     name: commit
     runs-on: ubuntu-latest
     steps:
      - name: jest test
      - uses: actions/setup-node@v1
        with:
            node-version: '14.x'

      - name: Install dependencies
        run: pnpm i

      - name: jest run
        run: pnpm run test & pnpm run coverage
